services:
  call-react:
    build: ./react
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.call-react.rule=Host(`call.mds.mondon.pro`)"
      - "traefik.http.routers.call-react.entrypoints=websecure"
      - "traefik.http.routers.call-react.tls.certresolver=myresolver"

  call-server:
    build: ./server
    volumes:
      - call-records:/app/records
      - call-fiche:/app/fiche
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.call-server.rule=Host(`api.call.mds.mondon.pro`)"
      - "traefik.http.services.call-server.loadbalancer.server.port=3003"
      - "traefik.http.routers.call-server.entrypoints=websecure"
      - "traefik.http.routers.call-server.tls.certresolver=myresolver"

  call-mongo:
    image: mongo:latest
    volumes:
      - call-mongo-data:/data/db

volumes:
  call-mongo-data:
    driver: local
  call-records:
    driver: local
  call-fiche:
    driver: local
