services:
  callmemaybe-react:
    container_name: callmemaybe-react
    build:
      context: ./react
      dockerfile: Dockerfile.dev
    command: sh -c "npm install && npm run dev -- --port 5174 --host 0.0.0.0"
    volumes:
      - ./react:/app
      - callmemaybe-react-node-modules:/app/node_modules
    ports:
      - "5174:5174"
    depends_on:
      - callmemaybe-server

  callmemaybe-server:
    container_name: callmemaybe-server
    build:
      context: ./server
      dockerfile: Dockerfile
    command: sh -c "npm install && nodemon server.js"
    volumes:
      - ./server:/app
      - callmemaybe-server-node-modules:/app/node_modules
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
    depends_on:
      - callmemaybe-mongo

  callmemaybe-mongo:
    container_name: callmemaybe-mongo
    image: mongo:latest
    volumes:
      - callmemaybe-mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  callmemaybe-mongo-data:
    driver: local
  callmemaybe-react-node-modules:
    driver: local
  callmemaybe-server-node-modules:
    driver: local