services:
  callmemaybe-react:
    container_name: callmemaybe-react
    build: ./react
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.callmemaybe-react.rule=Host(`call.mds.mondon.pro`)"
      - "traefik.http.routers.callmemaybe-react.entrypoints=websecure"
      - "traefik.http.routers.callmemaybe-react.tls.certresolver=myresolver"

  callmemaybe-server:
    container_name: callmemaybe-server
    build: ./server
    volumes:
      - callmemaybe-records:/app/records
      - callmemaybe-fiche:/app/fiche
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.callmemaybe-server.rule=Host(`api.call.mds.mondon.pro`)"
      - "traefik.http.services.callmemaybe-server.loadbalancer.server.port=3003"
      - "traefik.http.routers.callmemaybe-server.entrypoints=websecure"
      - "traefik.http.routers.callmemaybe-server.tls.certresolver=myresolver"

  callmemaybe-mongo:
    container_name: callmemaybe-mongo
    image: mongo:latest
    volumes:
      - callmemaybe-mongo-data:/data/db

volumes:
  callmemaybe-mongo-data:
    driver: local
  callmemaybe-records:
    driver: local
  callmemaybe-fiche:
    driver: local
