services:
  call-react:
    build:
      context: ./react
      dockerfile: Dockerfile.dev
    command: npm run dev -- --port 5174 --host 0.0.0.0
    volumes:
      - ./react:/app
      - react_node_modules:/app/node_modules
    ports:
      - "5174:5174"
    depends_on:
      - call-server

  call-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: nodemon server.js
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
    depends_on:
      - call-mongo

  call-mongo:
    image: mongo:latest
    volumes:
      - call-mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  call-mongo-data:
    driver: local
  react_node_modules:
    driver: local
  server_node_modules:
    driver: local